<!-- Begin Javascript
var strDomain;var numSites=0;var arraySites;var strHeaderImg;var strCreditImg;var strCreditAlt;var strCreditTitle;var strCreditLink;var strMobileLink;var strHelpLink;var strEmailLink;var bolPhone=true;var bolMobile=true;var bolHelp=true;var bolSize=true;var bolPrint=true;var bolEmail=true;
function hdrConfigs(){doPrintFriendly();if (window.location!=top.location) {top.location = window.location;}if (document.layers) {origWidth = innerWidth;origHeight = innerHeight;}if (document.layers) onresize = reloadPage;if(!strDomain){strDomain=getDomain();}if(numSites>0){strDomain=strDomain+setSubsites();}if(strHeaderImg){setStyle('hdrImgBlock','background-image:url("'+strHeaderImg+'");');}if(strCreditImg){setAttrib('hdrTxt','src',strCreditImg);}if(strCreditAlt){setAttrib('hdrTxt','alt',strCreditAlt);}if(strCreditTitle){setAttrib('hdrTxt','title',strCreditTitle);}if(strCreditLink){setAttrib('hdrTxtLink','href',strCreditLink);}if(strDomain){setAttrib('hdrSrchAg','value',strDomain);}if(strMobileLink){setAttrib('hdrMobileLink','href',strMobileLink);}if(strHelpLink){setAttrib('hdrHelpLink','href',strHelpLink);}if(strEmailLink){setAttrib('hdrEmailLink','href',strEmailLink);setAttrib('hdrEmailLink','onclick','');}if(bolPhone==false){setClass('p1c','hDiv');setClass('p1c_t','hDiv');}if(bolMobile==false){setClass('p2c','hDiv');setClass('p2c_t','hDiv');}if(bolHelp==false){setClass('p3c','hDiv');setClass('p3c_t','hDiv');}if(bolSize==false){setClass('p4c','hDiv');setClass('p4c_t','hDiv');}if(bolPrint==false){setClass('p5c','hDiv');setClass('p5c_t','hDiv');}if(bolEmail==false){setClass('p6c','hDiv');setClass('p6c_t','hDiv');}setAttrib('btns','align','right');setClass('btns','sDiv');}
function getDomain(){var sDom=location.href.toLowerCase();sDom=sDom.substr(0,sDom.indexOf('.gov')+4);if(sDom!='htt'){return sDom;}else{return 'http://delaware.gov'}}
function openPopup(url,w,h,winname){var winl=(screen.width - w) / 2;var wint=(screen.height - h) / 2;popupWin=window.open(url,winname,'toolbar=1,location=1,directories=0,status=1,menubar=1,resizable=1,scrollbars=1,top='+wint+',screenY='+wint+',left='+winl+',screenX='+winl+',width='+w+',innerWidth='+w+',height='+h+',innerHeight='+h);}
function popUpNew(Page,Width,Height,Scroll){window.open(Page,"popUpWindow",'width='+Width+',height='+Height+',toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars='+Scroll+',copyhistory=no,resizable=yes');}function reloadPage (){if (innerWidth != origWidth || innerHeight != origHeight) {location.reload();}}function changeScrollbarColor(C){if (document.all) {document.body.style.scrollbarBaseColor = C;}}function swapImage (name, source){var image;image = findDOMimage(name);image.src = source;}function setZIndex(objectName, newIndex){var refObject = findDOM(objectName,1);refObject.zIndex = newIndex;}function chgURL(frm){var url = frm.options[frm.selectedIndex].value;var ext = ".shtml";window.location.href = url + ext;}function antispam(name,domain){document.write = "mailto:" + name + "@" + domain;}function hideEmail(usr,dom,sub,dis){var user = usr;var domain = dom;var subj = sub;var display = dis;if (dis != '') {display = dis;}else{display = user + '@' + domain;}if (subj != '') {return ('<a href="mailto:'+user + '@' + domain +'?subject=' + subj + '">' + display + '</a>');}else{return ('<a href="mailto:'+user + '@' + domain + '">' + display + '</a>');}}function nonState(){if (confirm("The link you selected points to a \n non-State of Delaware website. \n Do you want to continue?")){return 1;}else{return 0;}}function setStyle(elm, style){document.getElementById(elm).setAttribute('style', style);document.getElementById(elm).style.cssText=style;}
function setStyle(elm,style){document.getElementById(elm).setAttribute('style', style);document.getElementById(elm).style.cssText=style;}
function setClass(elm,classname){document.getElementById(elm).setAttribute('class', classname);document.getElementById(elm).setAttribute('className', classname);}
function getAttrib(elm,attrib){document.getElementById(elm).getAttribute(attrib);}
function setAttrib(elm,attrib,newvalue){document.getElementById(elm).setAttribute(attrib,newvalue);}
function resetTabs(pre){var lis = document.getElementsByTagName('li');for (i=0; i<lis.length; i++){if(lis[i].id.indexOf(pre)!=-1){setClass(lis[i].id,'first');}}var divs = document.getElementsByTagName('div');for (i=0; i<divs.length; i++){if(divs[i].id.indexOf(pre)!=-1){setClass(divs[i].id,'hDiv');}}}		
function setTab(pre){setClass(pre+'l','selected');setClass(pre+'t','sDiv');}	
function setSubsites(){var sDom=location.href.toLowerCase();var sSite='';for (var i=1; i<=numSites; i++) {if(sDom.indexOf(arraySites[i])!=-1){sSite=arraySites[i];}}return sSite;}
function setFeatured(){return '<a href="'+strFeaturedLink+'"><img src="'+strFeaturedImg+'" alt="'+strFeaturedAlt+'" title="'+strFeaturedTitle+'" height="75" width="291" border="0"><\/a>';}
function setSearchOpt(){var sSOpt = '<label for="qp" title="Select the Focus of Your Search">';sSOpt = sSOpt + '<select name="qp" id="qp" class="search" tabindex="9">';sSOpt = sSOpt + '<option value="">Statewide<\/option>';sSOpt = sSOpt + '<option value="url:'+strDomain+'" selected>This Site<\/option>';sSOpt = sSOpt + '<\/select>';sSOpt = sSOpt + '<\/label>';return sSOpt;}
function setSearchReturn(){return '<input type="hidden" name="agencypage" value="'+strDomain+'"><!-- return button url -->';}
function togFontSize(cssID,strID,strFile,strOpt){if(strOpt==1){document.getElementById(strID+'Text').onclick=function(){togFontSize(cssID,strID,strFile,2);return false;};document.getElementById(strID+'Text').title='Increase Font Size';}else{document.getElementById(strID+'Text').onclick=function(){togFontSize(cssID,strID,strFile,1); return false;};document.getElementById(strID+'Text').title='Decrease Font Size';}cssSwitch(cssID,strID,strFile,strOpt);}
function cssSwitch(cssID,strID,strFile,strOpt){document.getElementById(cssID).href='/private/stylesheets/'+strFile+strOpt+'.css';}
function doPrintFriendly(){dom=location.href.toUpperCase();if(dom.indexOf("#PRINT")!=-1){cssSwitch('cssPrint','printToggle','print','2');setClass('hdrPrint','sDiv');document.getElementById('hdrPrint').innerHTML='<img src="http://www.delaware.gov/egov/portal.nsf/allfiles/images/$file/hdr_print.jpg" alt="State of Delaware">';}}
function resetDivs(pre,style){var divs = document.getElementsByTagName('div'); for (i=0; i<divs.length; i++){if(divs[i].id.indexOf(pre)!=-1){setStyle(divs[i].id,style);}}}
function hideDivs(pre){var divs = document.getElementsByTagName('div'); for (i=0; i<divs.length; i++){if(divs[i].id.indexOf(pre)!=-1){setClass(divs[i].id,'hDiv');}}}
function togView(elm){if(document.getElementById(elm).getAttribute('class')=='sDiv'){return true;}else{return false;}}
function showItem(pre,elm){var strSrch;if(elm=='head_srch_close'){strSrch=1;elm='head_srch';}if(togView(elm)==true){if(elm!='head_srch'||strSrch==1){setClass(elm,'hDiv');}setLinkDefaults();}else{hideDivs(pre);setClass(elm,'sDiv');setAttrib('hdrLogo','alt','');setAttrib('hdrLogo','title','');setAttrib('hdrLogoLink','href','#');setAttrib('hdrTxtLink','href','#');setAttrib('hdrTxt','alt','');setAttrib('hdrTxt','title','');}}
function setLinkDefaults(){setAttrib('hdrLogoLink','href','http://www.Delaware.gov');setAttrib('hdrLogo','alt','Photo: State of Delaware');setAttrib('hdrLogo','title','State of Delaware - The Official Website of the First State');setAttrib('hdrTxtLink','href',strCreditLink);setAttrib('hdrTxt','alt',strCreditAlt);setAttrib('hdrTxt','title',strCreditTitle);}
function doSlide(elm,style,time){setTimeout(function(){setStyle(elm, style);},time);}
function chkSrch(){if(document.getElementById('srchBox').value==''||document.getElementById('srchBox').value==' Your Search...'){alert('Please Enter a Search Keyword or Phrase');showItem('head_','head_srch');document.getElementById('srchBox').focus();document.getElementById('srchBox').value='';return false;}else{return true;}}
// End Javascript -->


